title: Ryder Cobean # your name (or website title) here
logo: "/images/face.png?raw=true" # your photo (or logo) here
description: > 
  Hi, I'm Ryder. I think, study, and work on how organizations can use tech to share nicely, remember things, make smart decisions, and save time. I'm pursuing a <a href="https://www.bu.edu/online/programs/graduate-programs/computer-information-systems-masters-degree/">Master of Science in Computer Information Systems from Boston University</a> to that end.
  <br><br>
  I have ten years' progressive experience in program and operational management, including design, budgeting, logistics, staff management, and donor relations.
  <br><br>
  When I'm not doing the things to the right of this column, I bake sourdough bread, make jam, ride my <a href="/images/trusty_steed.jpg">Trusty Steed</a>, and feed peanut butter to<a href="/images/cole.jpg"> Cole, my 72-lb greyhound</a>. 
  <br><br>
  <a href="https://www.linkedin.com/in/rydercobean/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

# Google Analytics
google_analytics: UA-147552359-1